title: Athena at Piccolo Portfolios
author: Athena Lam
email: Athena@piccoloportfolios.com
description: > # this means to ignore newlines until "show_exerpts:"
  Notes on content marketing, UX, and other observations on the web.
show_excerpts: true # set to true to show excerpts on the homepage
permalink: /:categories/:title:output_ext

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass
plainwhite:
  name: Athena Lam
  tagline: Content Strategist
  date_format: "%b %-d, %Y"
  sitemap: true # set to true to generate sitemap.xml content
  navigation:
    - title: Home
      url: "/index"
    - title: Categories
      url: "/categories"
    - title: Search
      url: "/search"  
    - title: About
      url: "/about"
    - title: Projects
      url: "/projects"
    - title: Call
      url: "https://calendly.com/athena-lam"


  # generate social links in footer
  social_links:
    twitter: shenchingtou
    github:  piccoloportfolios
    linkedIn: in/athenaylam
    rss: rss
    # dribbble: jekyll
    # facebook: jekyll
    # flickr:   jekyll
    # instagram: jekyll
    # linkedin: jekyll
    # pinterest: jekyll
    # youtube: jekyll
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon
    # telegram: jekyll
    # googleplus: +jekyll
    # microdotblog: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
theme: plainwhite

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jekyll-paginate

include: ['_pages']

paginate: 6
paginate_path: /page:num/

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
